# Generated by Django 4.0.6 on 2022-07-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('Feminino', 'Feminino'), ('Maculino', 'Maculino'), ('Outro', 'Outro')], max_length=10)),
                ('cpf', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('zip_code', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('road', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_point', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('three_char', models.CharField(max_length=255)),
                ('only_number', models.IntegerField()),
                ('single_char', models.CharField(max_length=255)),
                ('two_number', models.IntegerField()),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_vehicle', models.CharField(max_length=255)),
                ('model_vehicle', models.CharField(max_length=255)),
                ('model_year', models.IntegerField()),
                ('year_manufacture', models.IntegerField()),
                ('chassis', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.plate')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.vehicle')),
            ],
        ),
    ]
