# Generated by Django 4.0.6 on 2022-07-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='plate_id',
            new_name='plate',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
